"""empty message

Revision ID: 88e9abac9e79
Revises: e3ce2c3e7432
Create Date: 2021-03-06 23:39:10.683666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e9abac9e79'
down_revision = 'e3ce2c3e7432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brews', 'grain_bill')
    op.drop_column('brews', 'hop_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brews', sa.Column('hop_list', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('brews', sa.Column('grain_bill', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
