"""empty message

Revision ID: ee31934907cd
Revises: 31817ccdacd0
Create Date: 2021-03-13 02:49:48.818902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee31934907cd'
down_revision = '31817ccdacd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brews', 'yeast')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brews', sa.Column('yeast', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
