"""empty message

Revision ID: 8a08a11c1406
Revises: 1589c9c5917e
Create Date: 2021-03-10 00:41:27.569690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a08a11c1406'
down_revision = '1589c9c5917e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rotations', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rotations', 'updated_at')
    # ### end Alembic commands ###
