"""empty message

Revision ID: 50e8f0648489
Revises: 42e8fb5beeae
Create Date: 2021-03-07 17:09:09.453444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e8f0648489'
down_revision = '42e8fb5beeae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rotations', sa.Column('status', sa.String(length=25), nullable=False))
    op.drop_column('rotations', 'style')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rotations', sa.Column('style', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
    op.drop_column('rotations', 'status')
    # ### end Alembic commands ###
