"""empty message

Revision ID: 566eab5b008f
Revises: 8a08a11c1406
Create Date: 2021-03-13 01:40:42.883667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566eab5b008f'
down_revision = '8a08a11c1406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brews', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('brews', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('rotations', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rotations', 'created_at')
    op.drop_column('brews', 'updated_at')
    op.drop_column('brews', 'created_at')
    # ### end Alembic commands ###
