"""empty message

Revision ID: 4eb0daef2cbd
Revises: 60a27306be8a
Create Date: 2021-03-03 22:10:40.924121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb0daef2cbd'
down_revision = '60a27306be8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=25), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_measure', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(length=25), nullable=False),
    sa.Column('brew_name', sa.String(length=25), nullable=False),
    sa.Column('author', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('original_grav', sa.Float(), nullable=False),
    sa.Column('final_grav', sa.Float(), nullable=False),
    sa.Column('ferm_temp', sa.Integer(), nullable=False),
    sa.Column('primary_len', sa.String(), nullable=False),
    sa.Column('secondary_len', sa.String(), nullable=False),
    sa.Column('abv', sa.Float(), nullable=False),
    sa.Column('ibu', sa.Float(), nullable=False),
    sa.Column('srm', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follows',
    sa.Column('following_user', sa.Integer(), nullable=False),
    sa.Column('followed_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('following_user', 'followed_user')
    )
    op.create_table('brew_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brew_id', sa.Integer(), nullable=False),
    sa.Column('brew_day', sa.DateTime(), nullable=False),
    sa.Column('primary_end', sa.DateTime(), nullable=False),
    sa.Column('secondary_end', sa.DateTime(), nullable=True),
    sa.Column('bottling_day', sa.DateTime(), nullable=False),
    sa.Column('drinking_day', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brew_id'], ['brews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brew_ingredients',
    sa.Column('brew_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brew_id'], ['brews.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('brew_id', 'ingredient_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brew_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brew_id'], ['brews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brew_id', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['brew_id'], ['brews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rotations')
    op.drop_table('comments')
    op.drop_table('brew_ingredients')
    op.drop_table('brew_dates')
    op.drop_table('follows')
    op.drop_table('brews')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
