"""empty message

Revision ID: 185388896a98
Revises: 50e8f0648489
Create Date: 2021-03-07 17:16:34.899482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185388896a98'
down_revision = '50e8f0648489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('photos_url_key', 'photos', type_='unique')
    op.drop_column('photos', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('photos_url_key', 'photos', ['url'])
    # ### end Alembic commands ###
