"""empty message

Revision ID: 92d262a38697
Revises: 30b6d7e2fbc5
Create Date: 2021-03-07 20:17:49.301802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d262a38697'
down_revision = '30b6d7e2fbc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brews', sa.Column('author', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brews', 'author')
    # ### end Alembic commands ###
