"""empty message

Revision ID: 1589c9c5917e
Revises: 92d262a38697
Create Date: 2021-03-08 00:08:31.771746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1589c9c5917e'
down_revision = '92d262a38697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brews', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brews', sa.Column('author', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
